# permissions for end users to edit builders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: builder-editor-role
rules:
- apiGroups:
  - cpaas.redhat.com
  resources:
  - builders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cpaas.redhat.com
  resources:
  - builders/status
  verbs:
  - get
